[package]
name = "libcosmic"
version = "0.1.0"
edition = "2021"

[lib]
name = "cosmic"

[features]
default = []
debug = ["iced/debug"]

[dependencies]
freedesktop-icons = "0.2.1"
apply = "0.3.0"

[dependencies.iced]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
# path = "../iced"
features = ["cosmic-theme", "svg"]

[dependencies.iced_style]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
# path = "../iced/native"
features = ["cosmic-theme"]

[dependencies.iced_native]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
# path = "../iced/native"
features = ["cosmic-theme"]

[dependencies.iced_lazy]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
# path = "../iced/lazy"

[dependencies.iced_winit]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
# path = "../iced/winit"

[workspace]
members = [
  "examples/*",
  "gtk4",
  "gtk4/widgets"
]
